version: "3.8"

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # External:Internal mapping

  app2:
    build:
      context: ./app2
    ports:
      - "8082:8080" # External:Internal mapping

  app3:
    build:
      context: ./app3
    ports:
      - "8083:8080" # External:Internal mapping

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
