name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Docker and Docker Compose
      #   run: |
      #     # Update the package list and install prerequisites
      #     sudo apt-get update
      #     sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

      #     # Add Docker’s official GPG key
      #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

      #     # Set up the stable Docker repository
      #     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      #     # Install Docker Engine
      #     sudo apt-get update
      #     sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      #     # Install Docker Compose
      #     sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #     sudo chmod +x /usr/local/bin/docker-compose

      #     # Verify installation
      #     docker --version
      #     docker-compose --version

      # - name: Configure Docker Permissions
      #   run: |
      #     sudo groupadd docker || true
      #     sudo gpasswd -a $USER docker
      #     sudo service docker restart
      #     # Alternatively, avoid this for security reasons
      #     sudo chmod 666 /var/run/docker.sock

      - name: Deploy with Docker Compose
        run: |
          cd /home/ubuntu/actions-runner/_work/load-balancing/load-balancing
          docker-compose up -d

      # - name: Clean up dangling Docker images
      #   run: |
      #     docker image prune -f
