name: Install Docker on EC2

on:
  workflow_dispatch:
    inputs:
      ec2_ip:
        description: 'EC2 Instance IP'
        required: true
      ssh_private_key:
        description: 'SSH Private Key'
        required: true

jobs:
  install-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ github.event.inputs.ssh_private_key }}

    - name: Install Docker and Docker Compose
      env:
        EC2_HOST: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST '
          # Update package list
          sudo apt-get update

          # Install Docker
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

          # Add current user to docker group
          sudo usermod -aG docker $USER

          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Verify installations
          docker --version
          docker-compose --version
        '
